#!/usr/bin/env bash
# Quick commands for Docker Compose - Doctor's App

echo "=========================================="
echo "Doctor's App - Docker Quick Commands"
echo "=========================================="
echo ""
echo "🚀 START ALL SERVICES:"
echo "   docker-compose up -d"
echo ""
echo "🛑 STOP ALL SERVICES:"
echo "   docker-compose down"
echo ""
echo "📊 CHECK SERVICE STATUS:"
echo "   docker-compose ps"
echo ""
echo "📋 VIEW LOGS:"
echo "   docker-compose logs -f"
echo "   docker-compose logs -f backend"
echo "   docker-compose logs -f mongodb"
echo "   docker-compose logs -f mobile"
echo ""
echo "🔧 REBUILD IMAGES:"
echo "   docker-compose build --no-cache"
echo ""
echo "🔄 RESTART SERVICES:"
echo "   docker-compose restart backend"
echo "   docker-compose restart mongodb"
echo "   docker-compose restart mobile"
echo ""
echo "🐚 SHELL ACCESS:"
echo "   docker exec -it doctors_app_backend /bin/sh"
echo "   docker exec -it doctors_app_mongodb mongosh"
echo "   docker exec -it doctors_app_mobile /bin/bash"
echo ""
echo "🧹 CLEANUP:"
echo "   docker-compose down -v    # Remove volumes too"
echo "   docker system prune -a    # Clean unused resources"
echo ""
echo "🌐 SERVICE URLS:"
echo "   Backend API:    http://localhost:8080/api"
echo "   MongoDB:        localhost:27017"
echo "   Expo Mobile:    http://localhost:19000"
echo ""
echo "=========================================="
